In [14]:
%load_ext autoreload
%autoreload 2

%matplotlib notebook

import logging
logging.basicConfig()

from pathlib import Path
from pprint import pprint

from tqdm import tqdm, trange

import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv

import fish

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
NOTEBOOK_NAME = "domains"

HERE = Path.cwd().absolute()
DATA = HERE.parent / "data"
OUT = HERE / "out" / Path(NOTEBOOK_NAME).stem
print(HERE)
print(DATA)
print(OUT)


D:\projects\fish\dev
D:\projects\fish\data
D:\projects\fish\dev\out\domains


In [16]:
arr = np.arange(300).reshape((3, 10, 10))
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [17]:
d = fish.domain(arr, (0, 5, 5), (3, 5, 7))
print(d.shape)
d

(2, 5, 7)


array([[[ 32,  33,  34,  35,  36,  37,  38],
        [ 42,  43,  44,  45,  46,  47,  48],
        [ 52,  53,  54,  55,  56,  57,  58],
        [ 62,  63,  64,  65,  66,  67,  68],
        [ 72,  73,  74,  75,  76,  77,  78]],

       [[132, 133, 134, 135, 136, 137, 138],
        [142, 143, 144, 145, 146, 147, 148],
        [152, 153, 154, 155, 156, 157, 158],
        [162, 163, 164, 165, 166, 167, 168],
        [172, 173, 174, 175, 176, 177, 178]]])

In [18]:
for idxs, dom in fish.iter_domains(arr, (3, 5, 7)):
    print(idxs, dom.shape)
    print(dom)

(0, 0, 0) (2, 3, 4)
[[[  0   1   2   3]
  [ 10  11  12  13]
  [ 20  21  22  23]]

 [[100 101 102 103]
  [110 111 112 113]
  [120 121 122 123]]]
(0, 0, 1) (2, 3, 5)
[[[  0   1   2   3   4]
  [ 10  11  12  13  14]
  [ 20  21  22  23  24]]

 [[100 101 102 103 104]
  [110 111 112 113 114]
  [120 121 122 123 124]]]
(0, 0, 2) (2, 3, 6)
[[[  0   1   2   3   4   5]
  [ 10  11  12  13  14  15]
  [ 20  21  22  23  24  25]]

 [[100 101 102 103 104 105]
  [110 111 112 113 114 115]
  [120 121 122 123 124 125]]]
(0, 0, 3) (2, 3, 7)
[[[  0   1   2   3   4   5   6]
  [ 10  11  12  13  14  15  16]
  [ 20  21  22  23  24  25  26]]

 [[100 101 102 103 104 105 106]
  [110 111 112 113 114 115 116]
  [120 121 122 123 124 125 126]]]
(0, 0, 4) (2, 3, 7)
[[[  1   2   3   4   5   6   7]
  [ 11  12  13  14  15  16  17]
  [ 21  22  23  24  25  26  27]]

 [[101 102 103 104 105 106 107]
  [111 112 113 114 115 116 117]
  [121 122 123 124 125 126 127]]]
(0, 0, 5) (2, 3, 7)
[[[  2   3   4   5   6   7   8]
  [ 12  13  